### ISSUE TITLE
Error sometimes when setting column-width

### ISSUE THREAD

**Issue by abachborius2** [angular-gantt/angular-gantt#325]
```
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"getScrollableHeaderCss()","newVal":{"width":"202px"},"oldVal":{"width":"201px"}},{"msg":"getScrollableCss()","newVal":{"width":"202px"},"oldVal":{"width":"201px"}}],[{"msg":"getScrollableHeaderCss()","newVal":{"width":"201px"},"oldVal":{"width":"202px"}},{"msg":"getScrollableCss()","newVal":{"width":"201px"},"oldVal":{"width":"202px"}}],[{"msg":"getScrollableHeaderCss()","newVal":{"width":"202px"},"oldVal":{"width":"201px"}},{"msg":"getScrollableCss()","newVal":{"width":"202px"},"oldVal":{"width":"201px"}}],[{"msg":"getScrollableHeaderCss()","newVal":{"width":"201px"},"oldVal":{"width":"202px"}},{"msg":"getScrollableCss()","newVal":{"width":"201px"},"oldVal":{"width":"202px"}}],[{"msg":"getScrollableHeaderCss()","newVal":{"width":"202px"},"oldVal":{"width":"201px"}},{"msg":"getScrollableCss()","newVal":{"width":"202px"},"oldVal":{"width":"201px"}}]]
http://errors.angularjs.org/1.3.8/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22ms…3A%22202px%22%7D%2C%22oldVal%22%3A%7B%22width%22%3A%22201px%22%7D%7D%5D%5D
    at http://localhost/js/angular/angular.js:63:12
    at Scope.$digest (http://localhost/js/angular/angular.js:14263:19)
    at Scope.$apply (http://localhost/js/angular/angular.js:14488:24)
    at window.zoom (http://localhost/js/gantt.js:248:14)
    at <anonymous>:2:1
    at Object.InjectedScript._evaluateOn (<anonymous>:730:39)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:669:52)
    at Object.InjectedScript.evaluate (<anonymous>:581:21) angular.js:11594
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"getScrollableHeaderCss()","newVal":{"width":"202px"},"oldVal":{"width":"201px"}},{"msg":"getScrollableCss()","newVal":{"width":"202px"},"oldVal":{"width":"201px"}}],[{"msg":"getScrollableHeaderCss()","newVal":{"width":"201px"},"oldVal":{"width":"202px"}},{"msg":"getScrollableCss()","newVal":{"width":"201px"},"oldVal":{"width":"202px"}}],[{"msg":"getScrollableHeaderCss()","newVal":{"width":"202px"},"oldVal":{"width":"201px"}},{"msg":"getScrollableCss()","newVal":{"width":"202px"},"oldVal":{"width":"201px"}}],[{"msg":"getScrollableHeaderCss()","newVal":{"width":"201px"},"oldVal":{"width":"202px"}},{"msg":"getScrollableCss()","newVal":{"width":"201px"},"oldVal":{"width":"202px"}}],[{"msg":"getScrollableHeaderCss()","newVal":{"width":"202px"},"oldVal":{"width":"201px"}},{"msg":"getScrollableCss()","newVal":{"width":"202px"},"oldVal":{"width":"201px"}}]]
http://errors.angularjs.org/1.3.8/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22msg%22%3A%22getScrollableHeaderCss()%22%2C%22newVal%22%3A%7B%22width%22%3A%22202px%22%7D%2C%22oldVal%22%3A%7B%22width%22%3A%22201px%22%7D%7D%2C%7B%22msg%22%3A%22getScrollableCss()%22%2C%22newVal%22%3A%7B%22width%22%3A%22202px%22%7D%2C%22oldVal%22%3A%7B%22width%22%3A%22201px%22%7D%7D%5D%2C%5B%7B%22msg%22%3A%22getScrollableHeaderCss()%22%2C%22newVal%22%3A%7B%22width%22%3A%22201px%22%7D%2C%22oldVal%22%3A%7B%22width%22%3A%22202px%22%7D%7D%2C%7B%22msg%22%3A%22getScrollableCss()%22%2C%22newVal%22%3A%7B%22width%22%3A%22201px%22%7D%2C%22oldVal%22%3A%7B%22width%22%3A%22202px%22%7D%7D%5D%2C%5B%7B%22msg%22%3A%22getScrollableHeaderCss()%22%2C%22newVal%22%3A%7B%22width%22%3A%22202px%22%7D%2C%22oldVal%22%3A%7B%22width%22%3A%22201px%22%7D%7D%2C%7B%22msg%22%3A%22getScrollableCss()%22%2C%22newVal%22%3A%7B%22width%22%3A%22202px%22%7D%2C%22oldVal%22%3A%7B%22width%22%3A%22201px%22%7D%7D%5D%2C%5B%7B%22msg%22%3A%22getScrollableHeaderCss()%22%2C%22newVal%22%3A%7B%22width%22%3A%22201px%22%7D%2C%22oldVal%22%3A%7B%22width%22%3A%22202px%22%7D%7D%2C%7B%22msg%22%3A%22getScrollableCss()%22%2C%22newVal%22%3A%7B%22width%22%3A%22201px%22%7D%2C%22oldVal%22%3A%7B%22width%22%3A%22202px%22%7D%7D%5D%2C%5B%7B%22msg%22%3A%22getScrollableHeaderCss()%22%2C%22newVal%22%3A%7B%22width%22%3A%22202px%22%7D%2C%22oldVal%22%3A%7B%22width%22%3A%22201px%22%7D%7D%2C%7B%22msg%22%3A%22getScrollableCss()%22%2C%22newVal%22%3A%7B%22width%22%3A%22202px%22%7D%2C%22oldVal%22%3A%7B%22width%22%3A%22201px%22%7D%7D%5D%5D
```

In my particular case, it seems to happen whenever I set column-width to a multiple of 50.

**Comment by Toilal** [comment]
It seems that in some case, computed width value may be unstable. In your case, it's switching from 201 to 202 in an infinite $digest loop. I'll investigate.

**Comment by Toilal** [comment]
Do you have vertical scrollbar visible on the left of the component ? (using [max-height](https://www.angular-gantt.com/configuration/attributes/#max-height) option)

**Comment by Toilal** [comment]
@abachborius2, do you still have this issue ? It seems hard to reproduce, i think it depends on container size.

**Comment by abachborius2** [comment]
I added max-height and it does make the experience a little better, but it doesn't fix the bug.

**Comment by Toilal** [comment]
@abachborius2 Did you solve this issue ? I can't remember if we've worked on this together, and if it was fixed or not.

**Comment by mesutcakir** [comment]
I had this problem. I solved it with css for now. Please type if you find a better solution.

.gantt-scrollable {
    overflow: hidden;
    height: max-content;
}
