### ISSUE TITLE
Groups plugin $digest already in progress error

### ISSUE THREAD

**Issue by renekorss** [angular-gantt/angular-gantt#331]
I get this error on loading data.

````
Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.3.7/$rootScope/inprog?p0=%24digest
    at REGEX_STRING_REGEXP (http://localhost:9000/vendors/angular/angular.js:63:12)
    at beginPhase (http://localhost:9000/vendors/angular/angular.js:14735:15)
    at Scope.$get.Scope.$apply (http://localhost:9000/vendors/angular/angular.js:14479:11)
    at GanttApi.<anonymous> (http://localhost:9000/vendors/angular-gantt/assets/angular-gantt-plugins.js:1219:28)
    at http://localhost:9000/vendors/angular-gantt/assets/angular-gantt.js:210:33
    at Scope.$get.Scope.$broadcast (http://localhost:9000/vendors/angular/angular.js:14700:28)
    at Object.GanttApi.registerEvent.feature.raise.(anonymous function) [as change] (http://localhost:9000/vendors/angular-gantt/assets/angular-gantt.js:184:47)
    at Row.addTask (http://localhost:9000/vendors/angular-gantt/assets/angular-gantt.js:2373:60)
    at RowsManager.addRow (http://localhost:9000/vendors/angular-gantt/assets/angular-gantt.js:2684:25)
    at http://localhost:9000/vendors/angular-gantt/assets/angular-gantt.js:2080:46
````

**Comment by Toilal** [comment]
Thanks @renekorss . Should be fixed now.
