### ISSUE TITLE
api.core issue

### ISSUE THREAD

**Issue by messerschmitt755** [angular-gantt/angular-gantt#453]
Hi, I'm having toubles accessing a gantt API method. I need to use the following one:

**api.core.getDateByPosition(position)** 
Here's my angular code: 

```js
$scope.registerApi = function(api) {
        api.core.on.ready($scope, function () {
            $scope.ganttAPI = api;
            var pos = api.core.getDateByPosition($scope.position);
        });
    };
```

I filled the api attribute in my div and this function is launched.
When i debug, I can clearly see the methods of the API but when I access api.core.getDateByPosition(pos), I get the following error : 

**TypeError: Cannot read property 'getDateByPosition' of undefined**
    at ColumnsManager.expandExtendedColumnsForPosition (file:///C:/Code/Asset/angular-gantt/js/angular-gantt.js:1708:41)
    at ColumnsManager.getColumnByPosition (file:///C:/Code/Asset/angular-gantt/js/angular-gantt.js:1640:22)
    at Gantt.getDateByPosition (file:///C:/Code/Asset/angular-gantt/js/angular-gantt.js:2149:50)
    at Object.getDateByPosition (file:///C:/Code/Asset/angular-gantt/js/angular-gantt.js:3924:35)
    at GanttApi.<anonymous> (file:///C:/Code/Asset/angular-gantt/js/app.js:44:32)
    at file:///C:/Code/Asset/angular-gantt/js/angular-gantt.js:240:33
    at n.$get.n.$emit (file:///C:/Code/Asset/angular-gantt/js/angular.min.js:127:429)
    at Object.GanttApi.registerEvent.feature.raise.(anonymous function) [as ready] (file:///C:/Code/Asset/angular-gantt/js/angular-gantt.js:204:42)
    at Gantt.initialized (file:///C:/Code/Asset/angular-gantt/js/angular-gantt.js:2291:37)
    at file:///C:/Code/Asset/angular-gantt/js/angular-gantt.js:82:33

Some object in the class ColumnsManager is undefined and causes that.
Do you guys know where it comes from ? And how I can use this method properly ?
Thanks for your answer.

**Comment by messerschmitt755** [comment]
I

**Comment by messerschmitt755** [comment]
Actually, I was using the event api.core.on.ready() while I had to use api.core.on.rendered(), that's what caused the error. When ready, the gantt div attributes are undefined, meanwhile when it's rendered, the attributes are filled. Nice!
