### ISSUE TITLE
Urgent: Exception 

### ISSUE THREAD

**Issue by Schumii** [angular-gantt/angular-gantt#493]
Hi,
This is very urgent. I am getting this exception on rendering gantt randomly.

Uncaught TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at eval (eval at evaluate (unknown source), <anonymous>:1:6)
    at Object.InjectedScript._evaluateOn (<anonymous>:904:55)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:837:34)
    at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:963:21)
    at http://localhost:8080/lib/lib.js:122:267
    at http://localhost:8080/lib/lib.js:351:172
    at Object.fn (http://localhost:8080/lib/lib.js:239:30)
    at m.$digest (http://localhost:8080/lib/lib.js:240:114)
    at m.$apply (http://localhost:8080/lib/lib.js:243:12)

I can see $scope inside row which again has row object.
e.$scope.row.$scope.row.$scope

**Comment by Toilal** [comment]
Did you solved this error ? I think you have a circular reference in your model (a loop in row child/parent).

**Comment by Schumii** [comment]
it was because of duplicate row ids
