### ISSUE TITLE
TypeError: Cannot read property 'normalizeUnits' of undefined

### ISSUE THREAD

**Issue by blyssy** [angular-gantt/angular-gantt#541]
I am getting these errors at my console

TypeError: Cannot read property 'normalizeUnits' of undefined
    at Object.fn (gantt.factory.js:106)
    at n.a.$get.n.$digest (angular.js:15826)
    at n.a.$get.n.$apply (angular.js:16097)
    at angular.js:17864
    at e (angular.js:5507)
    at angular.js:5784

and then a bunch of

TypeError: Cannot read property 'isMoment' of undefined
    at n.b.gantt.$scope.simplifyMoment (http://localhost:3000/projects/assets/lib/angular-gantt/dist/angular-gantt.min.js:9:8393)
    at Object.fn [as get] (eval at <anonymous> (http://localhost:3000/bower_components/angular/angular.min.js:212:409), <anonymous>:4:336)
    at n.a.$get.n.$digest (http://localhost:3000/bower_components/angular/angular.min.js:130:348)
    at n.a.$get.n.$apply (http://localhost:3000/bower_components/angular/angular.min.js:133:512)
    at http://localhost:3000/bower_components/angular/angular.min.js:146:300
    at e (http://localhost:3000/bower_components/angular/angular.min.js:43:95)
    at http://localhost:3000/bower_components/angular/angular.min.js:45:491

I am developing with mean.io so my setup is a little different but not much.  In my custom package my app.js has

  Projects.aggregateAsset('js', '../lib/moment/moment.js');
  Projects.aggregateAsset('js', '../lib/angular-moment/angular-moment.min.js');
  Projects.aggregateAsset('css', '../lib/angular-gantt/dist/angular-gantt.min.css');
  Projects.aggregateAsset('js', '../lib/angular-gantt/dist/angular-gantt.min.js');
  Projects.aggregateAsset('css', '../lib/angular-gantt/dist/angular-gantt-plugins.min.css');
  Projects.aggregateAsset('js', '../lib/angular-gantt/dist/angular-gantt-plugins.min.js');

  Projects.angularDependencies(['angularMoment', 'gantt', 'gantt.table', 'gantt.movable', 'gantt.tooltips']);

my html is from the example docs with a couple of basic gantt directives and my $scope.data is also straight from the plunker example page.

Any idea what could be causing this problem?  Google is not much help with this one.  :)

**Comment by blyssy** [comment]
Found the issue.  As I suspected this is a mean.io specific issue.  You have to force the loading of js files.  changed my app.js to be

  Projects.aggregateAsset('js', '../lib/moment/moment.js', {global:true, weight: -1, group: 'footer'});
  Projects.aggregateAsset('js', '../lib/angular-moment/angular-moment.min.js', {global:true, weight: 0, group: 'footer'});
  Projects.aggregateAsset('css', '../lib/angular-gantt/dist/angular-gantt.min.css', {global:true});
  Projects.aggregateAsset('js', '../lib/angular-gantt/dist/angular-gantt.min.js', {global:true, weight: 1, group: 'footer'});
  Projects.aggregateAsset('css', '../lib/angular-gantt/dist/angular-gantt-plugins.min.css', {global:true});
  Projects.aggregateAsset('js', '../lib/angular-gantt/dist/angular-gantt-plugins.min.js', {global:true, weight: 2, group: 'footer'});

  Projects.angularDependencies(['angularMoment', 'gantt', 'gantt.table', 'gantt.movable', 'gantt.tooltips']);
