### ISSUE TITLE
Demo has errors in IE 11

### ISSUE THREAD

**Issue by vinsticSmith** [angular-gantt/angular-gantt#636]
```
Error: Invalid Params
   at interpolateFnWatchAction (https://www.angular-gantt.com/demo/scripts/vendor.js:9299:17)
   at interpolateFnWatcher (https://www.angular-gantt.com/demo/scripts/vendor.js:11832:17)
   at watchGroupAction (https://www.angular-gantt.com/demo/scripts/vendor.js:16334:13)
   at Scope.prototype.$digest (https://www.angular-gantt.com/demo/scripts/vendor.js:16664:23)
   at Scope.prototype.$apply (https://www.angular-gantt.com/demo/scripts/vendor.js:16928:13)
   at Anonymous function (https://www.angular-gantt.com/demo/scripts/vendor.js:18753:25)
   at completeOutstandingRequest (https://www.angular-gantt.com/demo/scripts/vendor.js:5804:7)
   at Anonymous function (https://www.angular-gantt.com/demo/scripts/vendor.js:6081:7)
```

**Comment by Toilal** [comment]
Wow :). Sorry I don't own windows.
