### ISSUE TITLE
Issue when loading the angular-gantt

### ISSUE THREAD

**Issue by ndpdarshana** [angular-gantt/angular-gantt#784]
Hi, I'm getting error when adding the gantt to angular module as described in the getting started guide.
```
Error: $injector:modulerr
Module Error
Failed to instantiate module centecDashboard due to:
Error: [$injector:modulerr] http://errors.angularjs.org/1.6.1/$injector/modulerr?p0=g...)
    at http://localhost:3000/bower_components/angular/angular.min.js:6:425
    at http://localhost:3000/bower_components/angular/angular.min.js:41:392
    at q (http://localhost:3000/bower_components/angular/angular.min.js:7:351)
    at g (http://localhost:3000/bower_components/angular/angular.min.js:40:488)
    at http://localhost:3000/bower_components/angular/angular.min.js:41:134
    at q (http://localhost:3000/bower_components/angular/angular.min.js:7:351)
    at g (http://localhost:3000/bower_components/angular/angular.min.js:40:488)
    at eb (http://localhost:3000/bower_components/angular/angular.min.js:45:56)
    at c (http://localhost:3000/bower_components/angular/angular.min.js:21:19)
    at Mc (http://localhost:3000/bower_components/angular/angular.min.js:21:332
``` 
I have imported the library using bower as follow. 
  "moment": "^2.18.1",
  "angular-gantt": "^1.3.3"

Can someone help me to sort out the issue?

**Comment by ndpdarshana** [comment]
Got resolved by importing angular-moment instead of momentjs package. 
https://github.com/urish/angular-moment

**Comment by Loksly** [comment]
This happened to me too, I guess should be considered to be somehow advised somewhere in the getting started section or considered as a bug.

**Comment by ndpdarshana** [comment]
Did you try with https://github.com/urish/angular-moment
